// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transit_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transit_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transit_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021007 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transit_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transit_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transit_5fdata_2eproto;
namespace Key {
class PremasterKeyRequest;
struct PremasterKeyRequestDefaultTypeInternal;
extern PremasterKeyRequestDefaultTypeInternal _PremasterKeyRequest_default_instance_;
class RandomKeyRespone;
struct RandomKeyResponeDefaultTypeInternal;
extern RandomKeyResponeDefaultTypeInternal _RandomKeyRespone_default_instance_;
class RandomNumRequest;
struct RandomNumRequestDefaultTypeInternal;
extern RandomNumRequestDefaultTypeInternal _RandomNumRequest_default_instance_;
class RequestMsg;
struct RequestMsgDefaultTypeInternal;
extern RequestMsgDefaultTypeInternal _RequestMsg_default_instance_;
class RespondMsg;
struct RespondMsgDefaultTypeInternal;
extern RespondMsgDefaultTypeInternal _RespondMsg_default_instance_;
}  // namespace Key
PROTOBUF_NAMESPACE_OPEN
template<> ::Key::PremasterKeyRequest* Arena::CreateMaybeMessage<::Key::PremasterKeyRequest>(Arena*);
template<> ::Key::RandomKeyRespone* Arena::CreateMaybeMessage<::Key::RandomKeyRespone>(Arena*);
template<> ::Key::RandomNumRequest* Arena::CreateMaybeMessage<::Key::RandomNumRequest>(Arena*);
template<> ::Key::RequestMsg* Arena::CreateMaybeMessage<::Key::RequestMsg>(Arena*);
template<> ::Key::RespondMsg* Arena::CreateMaybeMessage<::Key::RespondMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Key {

enum TYPE : int {
  RANDOMNUM = 0,
  PREKEY = 1,
  KEYCHECK = 2,
  KEYREVOKE = 3,
  TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TYPE_IsValid(int value);
constexpr TYPE TYPE_MIN = RANDOMNUM;
constexpr TYPE TYPE_MAX = KEYREVOKE;
constexpr int TYPE_ARRAYSIZE = TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TYPE_descriptor();
template<typename T>
inline const std::string& TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TYPE_descriptor(), enum_t_value);
}
inline bool TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TYPE>(
    TYPE_descriptor(), name, value);
}
enum RV : int {
  SUCCESS = 0,
  AUTHERR = 1,
  SERVERERR = 2,
  RV_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RV_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RV_IsValid(int value);
constexpr RV RV_MIN = SUCCESS;
constexpr RV RV_MAX = SERVERERR;
constexpr int RV_ARRAYSIZE = RV_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RV_descriptor();
template<typename T>
inline const std::string& RV_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RV>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RV_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RV_descriptor(), enum_t_value);
}
inline bool RV_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RV* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RV>(
    RV_descriptor(), name, value);
}
// ===================================================================

class RandomNumRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Key.RandomNumRequest) */ {
 public:
  inline RandomNumRequest() : RandomNumRequest(nullptr) {}
  ~RandomNumRequest() override;
  explicit PROTOBUF_CONSTEXPR RandomNumRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RandomNumRequest(const RandomNumRequest& from);
  RandomNumRequest(RandomNumRequest&& from) noexcept
    : RandomNumRequest() {
    *this = ::std::move(from);
  }

  inline RandomNumRequest& operator=(const RandomNumRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RandomNumRequest& operator=(RandomNumRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RandomNumRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RandomNumRequest* internal_default_instance() {
    return reinterpret_cast<const RandomNumRequest*>(
               &_RandomNumRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RandomNumRequest& a, RandomNumRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RandomNumRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RandomNumRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RandomNumRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RandomNumRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RandomNumRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RandomNumRequest& from) {
    RandomNumRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RandomNumRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Key.RandomNumRequest";
  }
  protected:
  explicit RandomNumRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRandomFieldNumber = 1,
  };
  // bytes random = 1;
  void clear_random();
  const std::string& random() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_random(ArgT0&& arg0, ArgT... args);
  std::string* mutable_random();
  PROTOBUF_NODISCARD std::string* release_random();
  void set_allocated_random(std::string* random);
  private:
  const std::string& _internal_random() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_random(const std::string& value);
  std::string* _internal_mutable_random();
  public:

  // @@protoc_insertion_point(class_scope:Key.RandomNumRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr random_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transit_5fdata_2eproto;
};
// -------------------------------------------------------------------

class RandomKeyRespone final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Key.RandomKeyRespone) */ {
 public:
  inline RandomKeyRespone() : RandomKeyRespone(nullptr) {}
  ~RandomKeyRespone() override;
  explicit PROTOBUF_CONSTEXPR RandomKeyRespone(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RandomKeyRespone(const RandomKeyRespone& from);
  RandomKeyRespone(RandomKeyRespone&& from) noexcept
    : RandomKeyRespone() {
    *this = ::std::move(from);
  }

  inline RandomKeyRespone& operator=(const RandomKeyRespone& from) {
    CopyFrom(from);
    return *this;
  }
  inline RandomKeyRespone& operator=(RandomKeyRespone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RandomKeyRespone& default_instance() {
    return *internal_default_instance();
  }
  static inline const RandomKeyRespone* internal_default_instance() {
    return reinterpret_cast<const RandomKeyRespone*>(
               &_RandomKeyRespone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RandomKeyRespone& a, RandomKeyRespone& b) {
    a.Swap(&b);
  }
  inline void Swap(RandomKeyRespone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RandomKeyRespone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RandomKeyRespone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RandomKeyRespone>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RandomKeyRespone& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RandomKeyRespone& from) {
    RandomKeyRespone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RandomKeyRespone* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Key.RandomKeyRespone";
  }
  protected:
  explicit RandomKeyRespone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRandomFieldNumber = 1,
    kKeyFieldNumber = 2,
  };
  // bytes random = 1;
  void clear_random();
  const std::string& random() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_random(ArgT0&& arg0, ArgT... args);
  std::string* mutable_random();
  PROTOBUF_NODISCARD std::string* release_random();
  void set_allocated_random(std::string* random);
  private:
  const std::string& _internal_random() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_random(const std::string& value);
  std::string* _internal_mutable_random();
  public:

  // bytes key = 2;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // @@protoc_insertion_point(class_scope:Key.RandomKeyRespone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr random_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transit_5fdata_2eproto;
};
// -------------------------------------------------------------------

class PremasterKeyRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Key.PremasterKeyRequest) */ {
 public:
  inline PremasterKeyRequest() : PremasterKeyRequest(nullptr) {}
  ~PremasterKeyRequest() override;
  explicit PROTOBUF_CONSTEXPR PremasterKeyRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PremasterKeyRequest(const PremasterKeyRequest& from);
  PremasterKeyRequest(PremasterKeyRequest&& from) noexcept
    : PremasterKeyRequest() {
    *this = ::std::move(from);
  }

  inline PremasterKeyRequest& operator=(const PremasterKeyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PremasterKeyRequest& operator=(PremasterKeyRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PremasterKeyRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PremasterKeyRequest* internal_default_instance() {
    return reinterpret_cast<const PremasterKeyRequest*>(
               &_PremasterKeyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PremasterKeyRequest& a, PremasterKeyRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PremasterKeyRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PremasterKeyRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PremasterKeyRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PremasterKeyRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PremasterKeyRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PremasterKeyRequest& from) {
    PremasterKeyRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PremasterKeyRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Key.PremasterKeyRequest";
  }
  protected:
  explicit PremasterKeyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPrekeyFieldNumber = 1,
  };
  // bytes prekey = 1;
  void clear_prekey();
  const std::string& prekey() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_prekey(ArgT0&& arg0, ArgT... args);
  std::string* mutable_prekey();
  PROTOBUF_NODISCARD std::string* release_prekey();
  void set_allocated_prekey(std::string* prekey);
  private:
  const std::string& _internal_prekey() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_prekey(const std::string& value);
  std::string* _internal_mutable_prekey();
  public:

  // @@protoc_insertion_point(class_scope:Key.PremasterKeyRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr prekey_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transit_5fdata_2eproto;
};
// -------------------------------------------------------------------

class RequestMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Key.RequestMsg) */ {
 public:
  inline RequestMsg() : RequestMsg(nullptr) {}
  ~RequestMsg() override;
  explicit PROTOBUF_CONSTEXPR RequestMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RequestMsg(const RequestMsg& from);
  RequestMsg(RequestMsg&& from) noexcept
    : RequestMsg() {
    *this = ::std::move(from);
  }

  inline RequestMsg& operator=(const RequestMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestMsg& operator=(RequestMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const RequestMsg* internal_default_instance() {
    return reinterpret_cast<const RequestMsg*>(
               &_RequestMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RequestMsg& a, RequestMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(RequestMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RequestMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RequestMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RequestMsg& from) {
    RequestMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RequestMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Key.RequestMsg";
  }
  protected:
  explicit RequestMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 2,
    kAuthCodeFieldNumber = 3,
    kServerIdFieldNumber = 4,
    kSignFieldNumber = 5,
    kDataFieldNumber = 6,
    kTypeFieldNumber = 1,
    kKeyidFieldNumber = 7,
  };
  // bytes clientId = 2;
  void clear_clientid();
  const std::string& clientid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_clientid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_clientid();
  PROTOBUF_NODISCARD std::string* release_clientid();
  void set_allocated_clientid(std::string* clientid);
  private:
  const std::string& _internal_clientid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(const std::string& value);
  std::string* _internal_mutable_clientid();
  public:

  // bytes authCode = 3;
  void clear_authcode();
  const std::string& authcode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_authcode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_authcode();
  PROTOBUF_NODISCARD std::string* release_authcode();
  void set_allocated_authcode(std::string* authcode);
  private:
  const std::string& _internal_authcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_authcode(const std::string& value);
  std::string* _internal_mutable_authcode();
  public:

  // bytes serverId = 4;
  void clear_serverid();
  const std::string& serverid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_serverid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_serverid();
  PROTOBUF_NODISCARD std::string* release_serverid();
  void set_allocated_serverid(std::string* serverid);
  private:
  const std::string& _internal_serverid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serverid(const std::string& value);
  std::string* _internal_mutable_serverid();
  public:

  // bytes sign = 5;
  void clear_sign();
  const std::string& sign() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sign(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sign();
  PROTOBUF_NODISCARD std::string* release_sign();
  void set_allocated_sign(std::string* sign);
  private:
  const std::string& _internal_sign() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sign(const std::string& value);
  std::string* _internal_mutable_sign();
  public:

  // bytes data = 6;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .Key.TYPE type = 1;
  void clear_type();
  ::Key::TYPE type() const;
  void set_type(::Key::TYPE value);
  private:
  ::Key::TYPE _internal_type() const;
  void _internal_set_type(::Key::TYPE value);
  public:

  // int32 keyid = 7;
  void clear_keyid();
  int32_t keyid() const;
  void set_keyid(int32_t value);
  private:
  int32_t _internal_keyid() const;
  void _internal_set_keyid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Key.RequestMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr clientid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr authcode_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serverid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sign_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int type_;
    int32_t keyid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transit_5fdata_2eproto;
};
// -------------------------------------------------------------------

class RespondMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Key.RespondMsg) */ {
 public:
  inline RespondMsg() : RespondMsg(nullptr) {}
  ~RespondMsg() override;
  explicit PROTOBUF_CONSTEXPR RespondMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RespondMsg(const RespondMsg& from);
  RespondMsg(RespondMsg&& from) noexcept
    : RespondMsg() {
    *this = ::std::move(from);
  }

  inline RespondMsg& operator=(const RespondMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline RespondMsg& operator=(RespondMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RespondMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const RespondMsg* internal_default_instance() {
    return reinterpret_cast<const RespondMsg*>(
               &_RespondMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RespondMsg& a, RespondMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(RespondMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RespondMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RespondMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RespondMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RespondMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RespondMsg& from) {
    RespondMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RespondMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Key.RespondMsg";
  }
  protected:
  explicit RespondMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 3,
    kServerIdFieldNumber = 4,
    kSignFieldNumber = 5,
    kAuthCodeFieldNumber = 6,
    kDataFieldNumber = 7,
    kTypeFieldNumber = 1,
    kRvFieldNumber = 2,
  };
  // bytes clientId = 3;
  void clear_clientid();
  const std::string& clientid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_clientid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_clientid();
  PROTOBUF_NODISCARD std::string* release_clientid();
  void set_allocated_clientid(std::string* clientid);
  private:
  const std::string& _internal_clientid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(const std::string& value);
  std::string* _internal_mutable_clientid();
  public:

  // bytes serverId = 4;
  void clear_serverid();
  const std::string& serverid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_serverid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_serverid();
  PROTOBUF_NODISCARD std::string* release_serverid();
  void set_allocated_serverid(std::string* serverid);
  private:
  const std::string& _internal_serverid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serverid(const std::string& value);
  std::string* _internal_mutable_serverid();
  public:

  // bytes sign = 5;
  void clear_sign();
  const std::string& sign() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_sign(ArgT0&& arg0, ArgT... args);
  std::string* mutable_sign();
  PROTOBUF_NODISCARD std::string* release_sign();
  void set_allocated_sign(std::string* sign);
  private:
  const std::string& _internal_sign() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sign(const std::string& value);
  std::string* _internal_mutable_sign();
  public:

  // bytes authCode = 6;
  void clear_authcode();
  const std::string& authcode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_authcode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_authcode();
  PROTOBUF_NODISCARD std::string* release_authcode();
  void set_allocated_authcode(std::string* authcode);
  private:
  const std::string& _internal_authcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_authcode(const std::string& value);
  std::string* _internal_mutable_authcode();
  public:

  // bytes data = 7;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .Key.TYPE type = 1;
  void clear_type();
  ::Key::TYPE type() const;
  void set_type(::Key::TYPE value);
  private:
  ::Key::TYPE _internal_type() const;
  void _internal_set_type(::Key::TYPE value);
  public:

  // .Key.RV rv = 2;
  void clear_rv();
  ::Key::RV rv() const;
  void set_rv(::Key::RV value);
  private:
  ::Key::RV _internal_rv() const;
  void _internal_set_rv(::Key::RV value);
  public:

  // @@protoc_insertion_point(class_scope:Key.RespondMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr clientid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serverid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr sign_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr authcode_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int type_;
    int rv_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transit_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RandomNumRequest

// bytes random = 1;
inline void RandomNumRequest::clear_random() {
  _impl_.random_.ClearToEmpty();
}
inline const std::string& RandomNumRequest::random() const {
  // @@protoc_insertion_point(field_get:Key.RandomNumRequest.random)
  return _internal_random();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RandomNumRequest::set_random(ArgT0&& arg0, ArgT... args) {
 
 _impl_.random_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RandomNumRequest.random)
}
inline std::string* RandomNumRequest::mutable_random() {
  std::string* _s = _internal_mutable_random();
  // @@protoc_insertion_point(field_mutable:Key.RandomNumRequest.random)
  return _s;
}
inline const std::string& RandomNumRequest::_internal_random() const {
  return _impl_.random_.Get();
}
inline void RandomNumRequest::_internal_set_random(const std::string& value) {
  
  _impl_.random_.Set(value, GetArenaForAllocation());
}
inline std::string* RandomNumRequest::_internal_mutable_random() {
  
  return _impl_.random_.Mutable(GetArenaForAllocation());
}
inline std::string* RandomNumRequest::release_random() {
  // @@protoc_insertion_point(field_release:Key.RandomNumRequest.random)
  return _impl_.random_.Release();
}
inline void RandomNumRequest::set_allocated_random(std::string* random) {
  if (random != nullptr) {
    
  } else {
    
  }
  _impl_.random_.SetAllocated(random, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.random_.IsDefault()) {
    _impl_.random_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RandomNumRequest.random)
}

// -------------------------------------------------------------------

// RandomKeyRespone

// bytes random = 1;
inline void RandomKeyRespone::clear_random() {
  _impl_.random_.ClearToEmpty();
}
inline const std::string& RandomKeyRespone::random() const {
  // @@protoc_insertion_point(field_get:Key.RandomKeyRespone.random)
  return _internal_random();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RandomKeyRespone::set_random(ArgT0&& arg0, ArgT... args) {
 
 _impl_.random_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RandomKeyRespone.random)
}
inline std::string* RandomKeyRespone::mutable_random() {
  std::string* _s = _internal_mutable_random();
  // @@protoc_insertion_point(field_mutable:Key.RandomKeyRespone.random)
  return _s;
}
inline const std::string& RandomKeyRespone::_internal_random() const {
  return _impl_.random_.Get();
}
inline void RandomKeyRespone::_internal_set_random(const std::string& value) {
  
  _impl_.random_.Set(value, GetArenaForAllocation());
}
inline std::string* RandomKeyRespone::_internal_mutable_random() {
  
  return _impl_.random_.Mutable(GetArenaForAllocation());
}
inline std::string* RandomKeyRespone::release_random() {
  // @@protoc_insertion_point(field_release:Key.RandomKeyRespone.random)
  return _impl_.random_.Release();
}
inline void RandomKeyRespone::set_allocated_random(std::string* random) {
  if (random != nullptr) {
    
  } else {
    
  }
  _impl_.random_.SetAllocated(random, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.random_.IsDefault()) {
    _impl_.random_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RandomKeyRespone.random)
}

// bytes key = 2;
inline void RandomKeyRespone::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& RandomKeyRespone::key() const {
  // @@protoc_insertion_point(field_get:Key.RandomKeyRespone.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RandomKeyRespone::set_key(ArgT0&& arg0, ArgT... args) {
 
 _impl_.key_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RandomKeyRespone.key)
}
inline std::string* RandomKeyRespone::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:Key.RandomKeyRespone.key)
  return _s;
}
inline const std::string& RandomKeyRespone::_internal_key() const {
  return _impl_.key_.Get();
}
inline void RandomKeyRespone::_internal_set_key(const std::string& value) {
  
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* RandomKeyRespone::_internal_mutable_key() {
  
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* RandomKeyRespone::release_key() {
  // @@protoc_insertion_point(field_release:Key.RandomKeyRespone.key)
  return _impl_.key_.Release();
}
inline void RandomKeyRespone::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RandomKeyRespone.key)
}

// -------------------------------------------------------------------

// PremasterKeyRequest

// bytes prekey = 1;
inline void PremasterKeyRequest::clear_prekey() {
  _impl_.prekey_.ClearToEmpty();
}
inline const std::string& PremasterKeyRequest::prekey() const {
  // @@protoc_insertion_point(field_get:Key.PremasterKeyRequest.prekey)
  return _internal_prekey();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PremasterKeyRequest::set_prekey(ArgT0&& arg0, ArgT... args) {
 
 _impl_.prekey_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.PremasterKeyRequest.prekey)
}
inline std::string* PremasterKeyRequest::mutable_prekey() {
  std::string* _s = _internal_mutable_prekey();
  // @@protoc_insertion_point(field_mutable:Key.PremasterKeyRequest.prekey)
  return _s;
}
inline const std::string& PremasterKeyRequest::_internal_prekey() const {
  return _impl_.prekey_.Get();
}
inline void PremasterKeyRequest::_internal_set_prekey(const std::string& value) {
  
  _impl_.prekey_.Set(value, GetArenaForAllocation());
}
inline std::string* PremasterKeyRequest::_internal_mutable_prekey() {
  
  return _impl_.prekey_.Mutable(GetArenaForAllocation());
}
inline std::string* PremasterKeyRequest::release_prekey() {
  // @@protoc_insertion_point(field_release:Key.PremasterKeyRequest.prekey)
  return _impl_.prekey_.Release();
}
inline void PremasterKeyRequest::set_allocated_prekey(std::string* prekey) {
  if (prekey != nullptr) {
    
  } else {
    
  }
  _impl_.prekey_.SetAllocated(prekey, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.prekey_.IsDefault()) {
    _impl_.prekey_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.PremasterKeyRequest.prekey)
}

// -------------------------------------------------------------------

// RequestMsg

// .Key.TYPE type = 1;
inline void RequestMsg::clear_type() {
  _impl_.type_ = 0;
}
inline ::Key::TYPE RequestMsg::_internal_type() const {
  return static_cast< ::Key::TYPE >(_impl_.type_);
}
inline ::Key::TYPE RequestMsg::type() const {
  // @@protoc_insertion_point(field_get:Key.RequestMsg.type)
  return _internal_type();
}
inline void RequestMsg::_internal_set_type(::Key::TYPE value) {
  
  _impl_.type_ = value;
}
inline void RequestMsg::set_type(::Key::TYPE value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Key.RequestMsg.type)
}

// bytes clientId = 2;
inline void RequestMsg::clear_clientid() {
  _impl_.clientid_.ClearToEmpty();
}
inline const std::string& RequestMsg::clientid() const {
  // @@protoc_insertion_point(field_get:Key.RequestMsg.clientId)
  return _internal_clientid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RequestMsg::set_clientid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.clientid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RequestMsg.clientId)
}
inline std::string* RequestMsg::mutable_clientid() {
  std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:Key.RequestMsg.clientId)
  return _s;
}
inline const std::string& RequestMsg::_internal_clientid() const {
  return _impl_.clientid_.Get();
}
inline void RequestMsg::_internal_set_clientid(const std::string& value) {
  
  _impl_.clientid_.Set(value, GetArenaForAllocation());
}
inline std::string* RequestMsg::_internal_mutable_clientid() {
  
  return _impl_.clientid_.Mutable(GetArenaForAllocation());
}
inline std::string* RequestMsg::release_clientid() {
  // @@protoc_insertion_point(field_release:Key.RequestMsg.clientId)
  return _impl_.clientid_.Release();
}
inline void RequestMsg::set_allocated_clientid(std::string* clientid) {
  if (clientid != nullptr) {
    
  } else {
    
  }
  _impl_.clientid_.SetAllocated(clientid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.clientid_.IsDefault()) {
    _impl_.clientid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RequestMsg.clientId)
}

// bytes authCode = 3;
inline void RequestMsg::clear_authcode() {
  _impl_.authcode_.ClearToEmpty();
}
inline const std::string& RequestMsg::authcode() const {
  // @@protoc_insertion_point(field_get:Key.RequestMsg.authCode)
  return _internal_authcode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RequestMsg::set_authcode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.authcode_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RequestMsg.authCode)
}
inline std::string* RequestMsg::mutable_authcode() {
  std::string* _s = _internal_mutable_authcode();
  // @@protoc_insertion_point(field_mutable:Key.RequestMsg.authCode)
  return _s;
}
inline const std::string& RequestMsg::_internal_authcode() const {
  return _impl_.authcode_.Get();
}
inline void RequestMsg::_internal_set_authcode(const std::string& value) {
  
  _impl_.authcode_.Set(value, GetArenaForAllocation());
}
inline std::string* RequestMsg::_internal_mutable_authcode() {
  
  return _impl_.authcode_.Mutable(GetArenaForAllocation());
}
inline std::string* RequestMsg::release_authcode() {
  // @@protoc_insertion_point(field_release:Key.RequestMsg.authCode)
  return _impl_.authcode_.Release();
}
inline void RequestMsg::set_allocated_authcode(std::string* authcode) {
  if (authcode != nullptr) {
    
  } else {
    
  }
  _impl_.authcode_.SetAllocated(authcode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.authcode_.IsDefault()) {
    _impl_.authcode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RequestMsg.authCode)
}

// bytes serverId = 4;
inline void RequestMsg::clear_serverid() {
  _impl_.serverid_.ClearToEmpty();
}
inline const std::string& RequestMsg::serverid() const {
  // @@protoc_insertion_point(field_get:Key.RequestMsg.serverId)
  return _internal_serverid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RequestMsg::set_serverid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.serverid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RequestMsg.serverId)
}
inline std::string* RequestMsg::mutable_serverid() {
  std::string* _s = _internal_mutable_serverid();
  // @@protoc_insertion_point(field_mutable:Key.RequestMsg.serverId)
  return _s;
}
inline const std::string& RequestMsg::_internal_serverid() const {
  return _impl_.serverid_.Get();
}
inline void RequestMsg::_internal_set_serverid(const std::string& value) {
  
  _impl_.serverid_.Set(value, GetArenaForAllocation());
}
inline std::string* RequestMsg::_internal_mutable_serverid() {
  
  return _impl_.serverid_.Mutable(GetArenaForAllocation());
}
inline std::string* RequestMsg::release_serverid() {
  // @@protoc_insertion_point(field_release:Key.RequestMsg.serverId)
  return _impl_.serverid_.Release();
}
inline void RequestMsg::set_allocated_serverid(std::string* serverid) {
  if (serverid != nullptr) {
    
  } else {
    
  }
  _impl_.serverid_.SetAllocated(serverid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.serverid_.IsDefault()) {
    _impl_.serverid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RequestMsg.serverId)
}

// bytes sign = 5;
inline void RequestMsg::clear_sign() {
  _impl_.sign_.ClearToEmpty();
}
inline const std::string& RequestMsg::sign() const {
  // @@protoc_insertion_point(field_get:Key.RequestMsg.sign)
  return _internal_sign();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RequestMsg::set_sign(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sign_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RequestMsg.sign)
}
inline std::string* RequestMsg::mutable_sign() {
  std::string* _s = _internal_mutable_sign();
  // @@protoc_insertion_point(field_mutable:Key.RequestMsg.sign)
  return _s;
}
inline const std::string& RequestMsg::_internal_sign() const {
  return _impl_.sign_.Get();
}
inline void RequestMsg::_internal_set_sign(const std::string& value) {
  
  _impl_.sign_.Set(value, GetArenaForAllocation());
}
inline std::string* RequestMsg::_internal_mutable_sign() {
  
  return _impl_.sign_.Mutable(GetArenaForAllocation());
}
inline std::string* RequestMsg::release_sign() {
  // @@protoc_insertion_point(field_release:Key.RequestMsg.sign)
  return _impl_.sign_.Release();
}
inline void RequestMsg::set_allocated_sign(std::string* sign) {
  if (sign != nullptr) {
    
  } else {
    
  }
  _impl_.sign_.SetAllocated(sign, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sign_.IsDefault()) {
    _impl_.sign_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RequestMsg.sign)
}

// bytes data = 6;
inline void RequestMsg::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& RequestMsg::data() const {
  // @@protoc_insertion_point(field_get:Key.RequestMsg.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RequestMsg::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RequestMsg.data)
}
inline std::string* RequestMsg::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Key.RequestMsg.data)
  return _s;
}
inline const std::string& RequestMsg::_internal_data() const {
  return _impl_.data_.Get();
}
inline void RequestMsg::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* RequestMsg::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* RequestMsg::release_data() {
  // @@protoc_insertion_point(field_release:Key.RequestMsg.data)
  return _impl_.data_.Release();
}
inline void RequestMsg::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RequestMsg.data)
}

// int32 keyid = 7;
inline void RequestMsg::clear_keyid() {
  _impl_.keyid_ = 0;
}
inline int32_t RequestMsg::_internal_keyid() const {
  return _impl_.keyid_;
}
inline int32_t RequestMsg::keyid() const {
  // @@protoc_insertion_point(field_get:Key.RequestMsg.keyid)
  return _internal_keyid();
}
inline void RequestMsg::_internal_set_keyid(int32_t value) {
  
  _impl_.keyid_ = value;
}
inline void RequestMsg::set_keyid(int32_t value) {
  _internal_set_keyid(value);
  // @@protoc_insertion_point(field_set:Key.RequestMsg.keyid)
}

// -------------------------------------------------------------------

// RespondMsg

// .Key.TYPE type = 1;
inline void RespondMsg::clear_type() {
  _impl_.type_ = 0;
}
inline ::Key::TYPE RespondMsg::_internal_type() const {
  return static_cast< ::Key::TYPE >(_impl_.type_);
}
inline ::Key::TYPE RespondMsg::type() const {
  // @@protoc_insertion_point(field_get:Key.RespondMsg.type)
  return _internal_type();
}
inline void RespondMsg::_internal_set_type(::Key::TYPE value) {
  
  _impl_.type_ = value;
}
inline void RespondMsg::set_type(::Key::TYPE value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:Key.RespondMsg.type)
}

// .Key.RV rv = 2;
inline void RespondMsg::clear_rv() {
  _impl_.rv_ = 0;
}
inline ::Key::RV RespondMsg::_internal_rv() const {
  return static_cast< ::Key::RV >(_impl_.rv_);
}
inline ::Key::RV RespondMsg::rv() const {
  // @@protoc_insertion_point(field_get:Key.RespondMsg.rv)
  return _internal_rv();
}
inline void RespondMsg::_internal_set_rv(::Key::RV value) {
  
  _impl_.rv_ = value;
}
inline void RespondMsg::set_rv(::Key::RV value) {
  _internal_set_rv(value);
  // @@protoc_insertion_point(field_set:Key.RespondMsg.rv)
}

// bytes clientId = 3;
inline void RespondMsg::clear_clientid() {
  _impl_.clientid_.ClearToEmpty();
}
inline const std::string& RespondMsg::clientid() const {
  // @@protoc_insertion_point(field_get:Key.RespondMsg.clientId)
  return _internal_clientid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RespondMsg::set_clientid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.clientid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RespondMsg.clientId)
}
inline std::string* RespondMsg::mutable_clientid() {
  std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:Key.RespondMsg.clientId)
  return _s;
}
inline const std::string& RespondMsg::_internal_clientid() const {
  return _impl_.clientid_.Get();
}
inline void RespondMsg::_internal_set_clientid(const std::string& value) {
  
  _impl_.clientid_.Set(value, GetArenaForAllocation());
}
inline std::string* RespondMsg::_internal_mutable_clientid() {
  
  return _impl_.clientid_.Mutable(GetArenaForAllocation());
}
inline std::string* RespondMsg::release_clientid() {
  // @@protoc_insertion_point(field_release:Key.RespondMsg.clientId)
  return _impl_.clientid_.Release();
}
inline void RespondMsg::set_allocated_clientid(std::string* clientid) {
  if (clientid != nullptr) {
    
  } else {
    
  }
  _impl_.clientid_.SetAllocated(clientid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.clientid_.IsDefault()) {
    _impl_.clientid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RespondMsg.clientId)
}

// bytes serverId = 4;
inline void RespondMsg::clear_serverid() {
  _impl_.serverid_.ClearToEmpty();
}
inline const std::string& RespondMsg::serverid() const {
  // @@protoc_insertion_point(field_get:Key.RespondMsg.serverId)
  return _internal_serverid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RespondMsg::set_serverid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.serverid_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RespondMsg.serverId)
}
inline std::string* RespondMsg::mutable_serverid() {
  std::string* _s = _internal_mutable_serverid();
  // @@protoc_insertion_point(field_mutable:Key.RespondMsg.serverId)
  return _s;
}
inline const std::string& RespondMsg::_internal_serverid() const {
  return _impl_.serverid_.Get();
}
inline void RespondMsg::_internal_set_serverid(const std::string& value) {
  
  _impl_.serverid_.Set(value, GetArenaForAllocation());
}
inline std::string* RespondMsg::_internal_mutable_serverid() {
  
  return _impl_.serverid_.Mutable(GetArenaForAllocation());
}
inline std::string* RespondMsg::release_serverid() {
  // @@protoc_insertion_point(field_release:Key.RespondMsg.serverId)
  return _impl_.serverid_.Release();
}
inline void RespondMsg::set_allocated_serverid(std::string* serverid) {
  if (serverid != nullptr) {
    
  } else {
    
  }
  _impl_.serverid_.SetAllocated(serverid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.serverid_.IsDefault()) {
    _impl_.serverid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RespondMsg.serverId)
}

// bytes sign = 5;
inline void RespondMsg::clear_sign() {
  _impl_.sign_.ClearToEmpty();
}
inline const std::string& RespondMsg::sign() const {
  // @@protoc_insertion_point(field_get:Key.RespondMsg.sign)
  return _internal_sign();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RespondMsg::set_sign(ArgT0&& arg0, ArgT... args) {
 
 _impl_.sign_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RespondMsg.sign)
}
inline std::string* RespondMsg::mutable_sign() {
  std::string* _s = _internal_mutable_sign();
  // @@protoc_insertion_point(field_mutable:Key.RespondMsg.sign)
  return _s;
}
inline const std::string& RespondMsg::_internal_sign() const {
  return _impl_.sign_.Get();
}
inline void RespondMsg::_internal_set_sign(const std::string& value) {
  
  _impl_.sign_.Set(value, GetArenaForAllocation());
}
inline std::string* RespondMsg::_internal_mutable_sign() {
  
  return _impl_.sign_.Mutable(GetArenaForAllocation());
}
inline std::string* RespondMsg::release_sign() {
  // @@protoc_insertion_point(field_release:Key.RespondMsg.sign)
  return _impl_.sign_.Release();
}
inline void RespondMsg::set_allocated_sign(std::string* sign) {
  if (sign != nullptr) {
    
  } else {
    
  }
  _impl_.sign_.SetAllocated(sign, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.sign_.IsDefault()) {
    _impl_.sign_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RespondMsg.sign)
}

// bytes authCode = 6;
inline void RespondMsg::clear_authcode() {
  _impl_.authcode_.ClearToEmpty();
}
inline const std::string& RespondMsg::authcode() const {
  // @@protoc_insertion_point(field_get:Key.RespondMsg.authCode)
  return _internal_authcode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RespondMsg::set_authcode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.authcode_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RespondMsg.authCode)
}
inline std::string* RespondMsg::mutable_authcode() {
  std::string* _s = _internal_mutable_authcode();
  // @@protoc_insertion_point(field_mutable:Key.RespondMsg.authCode)
  return _s;
}
inline const std::string& RespondMsg::_internal_authcode() const {
  return _impl_.authcode_.Get();
}
inline void RespondMsg::_internal_set_authcode(const std::string& value) {
  
  _impl_.authcode_.Set(value, GetArenaForAllocation());
}
inline std::string* RespondMsg::_internal_mutable_authcode() {
  
  return _impl_.authcode_.Mutable(GetArenaForAllocation());
}
inline std::string* RespondMsg::release_authcode() {
  // @@protoc_insertion_point(field_release:Key.RespondMsg.authCode)
  return _impl_.authcode_.Release();
}
inline void RespondMsg::set_allocated_authcode(std::string* authcode) {
  if (authcode != nullptr) {
    
  } else {
    
  }
  _impl_.authcode_.SetAllocated(authcode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.authcode_.IsDefault()) {
    _impl_.authcode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RespondMsg.authCode)
}

// bytes data = 7;
inline void RespondMsg::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& RespondMsg::data() const {
  // @@protoc_insertion_point(field_get:Key.RespondMsg.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RespondMsg::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Key.RespondMsg.data)
}
inline std::string* RespondMsg::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:Key.RespondMsg.data)
  return _s;
}
inline const std::string& RespondMsg::_internal_data() const {
  return _impl_.data_.Get();
}
inline void RespondMsg::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* RespondMsg::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* RespondMsg::release_data() {
  // @@protoc_insertion_point(field_release:Key.RespondMsg.data)
  return _impl_.data_.Release();
}
inline void RespondMsg::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Key.RespondMsg.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Key

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Key::TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Key::TYPE>() {
  return ::Key::TYPE_descriptor();
}
template <> struct is_proto_enum< ::Key::RV> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Key::RV>() {
  return ::Key::RV_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transit_5fdata_2eproto
